<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>Main.App</StartupObject>
    <AssemblyName>lit</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <WindowsPackageType>None</WindowsPackageType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
  </PropertyGroup>
    <Target Name="DeployBuildOutput" AfterTargets="Build">
        <PropertyGroup>
            <DeployDirectory>I:\GitHubRepositories\WindowsTerminalLauncher\artifacts\deploy\</DeployDirectory>
        </PropertyGroup>

        <ItemGroup>
            <DeployFiles Include="$(TargetDir)**\*" />
        </ItemGroup>

        <MakeDir Directories="$(DeployDirectory)" />

        <Copy SourceFiles="@(DeployFiles)" DestinationFiles="@(DeployFiles->'$(DeployDirectory)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.335">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\config.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
